name: I Do Wedding Video
favicon: null
layout_spectrum: 0.24628
typography_spectrum: 0.7939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d3c8'
    - '#131114'
    - '#9b9fba'
    - '#433d3b'
    - '#7b7c92'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
