name: I Do Wedding Video
favicon: null
layout_spectrum: 0.49896
typography_spectrum: 0.36124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#31221d'
    - '#646a66'
    - '#9fb2b1'
    - '#7e133b'
  brandStrength: 0
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
