name: I Do Wedding Video
favicon: null
layout_spectrum: 0.7284
typography_spectrum: 0.22417
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8f2'
    - '#776f6c'
    - '#393f59'
    - '#b9a99a'
    - '#071b1c'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
