name: I Do Wedding Video
favicon: null
layout_spectrum: 0.49896
typography_spectrum: 0.36124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1714'
    - '#53443d'
    - '#887263'
    - '#bfa586'
    - '#fbfddf'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
